server:
  port: 9001

spring:
  application:
    name: auth-service
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true

jwt:
  secret-key: e0ea87012f32efe4126testKey54gkp54gfh277412b5513cec
  expiration: 86400
  issuer: https://ibetarsync.vercel.app/
