server:
  port: 9001

spring:
  application:
    name: auth-service
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true

jwt:
  secret-key:
  expiration: 86400
  issuer: https://ibetarsync.vercel.app/
