server:
  port: 9004

spring:
  application:
    name: email-service

eureka:
  client:
    service-url:
      defaultZOne: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}:${instanceId:${random.value}}

Kafka:
  bootstrapAddress: localhost:9092